apiVersion: v1
kind: Service
metadata:
  name: isinaj-service
spec:
  selector:
    app: isinaj
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

apiVersion: apps/v1
kind: Deployment
metadata:
  name: isinaj
spec:
  selector:
    matchLabels:
      app: isinaj
  replicas: 2
  template:
    metadata:
      labels:
        app: isinaj
    spec:
      containers:
      - name: isinaj
        image: isinaj:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
